CREATE TABLE users (
    user_id                           BIGSERIAL NOT NULL,
    create_ts                         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role                              CHAR(1)   NOT NULL DEFAULT 'U',
    activated                         CHAR(1)   DEFAULT 'Y',
    name                              VARCHAR(151) NOT NULL,
    a_street                          VARCHAR(151) DEFAULT '',
    a_city                            VARCHAR(51)  DEFAULT '',
    a_state                           VARCHAR(51)  DEFAULT '',
    a_pincode                         VARCHAR(11)  DEFAULT '',
    a_country                         VARCHAR(51)  DEFAULT '',
    locality_id                       INT4,
    locality                          VARCHAR(151),
    longitude                         FLOAT8,
    latitude                          FLOAT8,
    phone                             VARCHAR(101) DEFAULT '',
    e_verified                        CHAR(1) DEFAULT 'N',
    e_activated                       CHAR(1) DEFAULT 'N',
    email                             VARCHAR(101) DEFAULT NULL,
    m_verified                        CHAR(1) DEFAULT 'N',
    m_activated                       CHAR(1) DEFAULT 'N',
    mobile                            VARCHAR(16) DEFAULT NULL,
    mbl_network                       VARCHAR(10) DEFAULT NULL,
    mbl_handset                       VARCHAR(101) DEFAULT NULL,
    cc_id                             INT4 DEFAULT NULL,
    password                          VARCHAR(101) NOT NULL,
    txn_password                      VARCHAR(101),
    txn_pin                           VARCHAR(10),
    comments                          TEXT,
    is_new                            CHAR(1),

    roletype                          INTEGER DEFAULT 0,
    pagetype                          INTEGER,
    pageownerid                       BIGINT DEFAULT 0,
    adminids                          VARCHAR(256),
    useracl                           BIGINT DEFAULT 0,
    uuid                              VARCHAR(36) UNIQUE,
    version                           INT4,
    profile_pic_url                   VARCHAR(128),
    isloggedin                        BOOLEAN,
    login_partner_id                  INT4 DEFAULT -1,

    admin                             VARCHAR(101),
    grade                             VARCHAR(100),
    managed_by                        VARCHAR(101),
    referred_by                       VARCHAR(101),
    referenced_by                     INT4,
    distributor_id                    INT4,
    master_reseller_id                INTEGER DEFAULT -1,
    is_franchisee                     BOOLEAN,
    is_consolidator                   BOOLEAN,
    is_b2b_corporate                  BOOLEAN,
    outlet_type                       INT4,
    potential                         INT4,
    so_code                           VARCHAR(50),
    ro_code                           VARCHAR(50),
    rm_code                           VARCHAR(50),
    lastbookingdate                   DATE,
    user_rating                       INT4,
    raja_points                       INT4,
    base_currency                     CHAR(3),
    deposit                           BIGINT,
    credit_balance                    BIGINT,
    max_credit_balance                BIGINT,
    cash_limit                        BIGINT,
    rolling_credit_max                INT4,
    rolling_credit_exhausted          INT4,
    is_credit_enabled                 BOOLEAN,
    is_credit_card_enabled            BOOLEAN,
    is_deposit_enabled                BOOLEAN,
    is_dist_credit_enabled            BOOLEAN,
    is_via_onetime_credit_enabled     BOOLEAN,
    dist_credit_utilized              BIGINT,
    dist_credit_onetime               INT4,
    dist_credit_rolling               BIGINT,
    dist_credit_locktime              TIMESTAMP,
    credit_lock_date                  TIMESTAMP,
    low_balance_alert_limit           INT4,
    commission_rate                   NUMERIC(5,2),
    hotel_commission_rate             NUMERIC(5,2),
    hotel_sa_commission_rate          NUMERIC(5,2),
    bus_sa_commission_rate            NUMERIC(5,2),
    package_sa_commission_rate        NUMERIC(5,2) DEFAULT 2.0,
    movie_sa_commission_rate          NUMERIC(5,2),
    topup_commission_rate             NUMERIC(5,2) DEFAULT 2.0,
    topup_sa_commission_rate          NUMERIC(5,2),
    topup_commplan_id                 INT4,
    flight_comm_plan_id               INT4 DEFAULT -1,
    flight_commissions                TEXT,
    agent_markup                      TEXT,
    tds_rate                          NUMERIC(5,2),
    tds_slab                          INT4,
    partner_id                        INT4 DEFAULT -1,
    is_railways_enabled               BOOLEAN,
    is_topup_enabled                  BOOLEAN,
    is_movie_enabled                  BOOLEAN,
    is_ksrtc_enabled                  BOOLEAN,
    is_charge_payment_fee             BOOLEAN,
    is_give_plb_despite_no_payment_fee BOOLEAN,
    cug                               BOOLEAN,
    net_banking_enabled               BOOLEAN,
    user_priveledges                  VARCHAR(101),
    prefix_code                       VARCHAR(20),
    CONSTRAINT pk_users PRIMARY KEY (user_id),

    CONSTRAINT users_email_key  UNIQUE (role, email, login_partner_id),
    CONSTRAINT users_mobile_key UNIQUE (role, mobile, login_partner_id)
);

CREATE TABLE user_hist (
    user_id   BIGINT NOT NULL,
    create_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    history   TEXT NOT NULL,
    CONSTRAINT pk_uhist FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
